/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Consultar_Soluciones.java
 *
 * Created on 28-01-2012, 05:51:43 PM
 */

package grafica;

import java.awt.Dimension;

/**
 *
 * @author Marcial
 */
public class Consultar_Soluciones extends javax.swing.JFrame {


	ArbolNombres arbol_nombres;
	ArbolSintomas arbol_sintomas;

    /** Creates new form Consultar_Soluciones */
    public Consultar_Soluciones(ArbolNombres arbol_nombres, ArbolSintomas arbol_sintomas) {
        initComponents();

	this.arbol_nombres=arbol_nombres;
	this.arbol_sintomas=arbol_sintomas;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Sustancias.jpg"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.setBounds(30, 30, 153, 155);
        jDesktopPane1.add(jButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Sintomas.jpg"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jButton2.setBounds(210, 30, 163, 157);
        jDesktopPane1.add(jButton2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Sustancia.jpg"))); // NOI18N
        jLabel1.setBounds(60, 190, 87, 36);
        jDesktopPane1.add(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Sintomas 2.jpg"))); // NOI18N
        jLabel2.setBounds(250, 190, 80, 36);
        jDesktopPane1.add(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Sustancia ventana2_1 = new Sustancia(this.arbol_nombres, this.arbol_sintomas);
        Dimension dlgSize = ventana2_1.getPreferredSize();
        Dimension pantalla = getSize();
        Dimension ventana = ventana2_1.getSize() ;
        ventana2_1.setLocation((pantalla.width - Sustancia.WIDTH ) / 2 ,(pantalla.height - Sustancia.HEIGHT) / 2);
        ventana2_1.setLocationRelativeTo(null) ; // CENTRA EL SEGUNDO FRAME EN LA PANTA
        ventana2_1.pack() ;
        ventana2_1.setResizable(true) ; // PERMITE REDIMENSIONAR
        ventana2_1.setVisible(true) ;
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Sintomas ventana2_2 = new Sintomas(this.arbol_nombres, this.arbol_sintomas);
        Dimension dlgSize = ventana2_2.getPreferredSize();
        Dimension pantalla = getSize();
        Dimension ventana = ventana2_2.getSize() ;
        ventana2_2.setLocation((pantalla.width - Sintomas.WIDTH ) / 2 ,(pantalla.height - Sintomas.HEIGHT) / 2);
        ventana2_2.setLocationRelativeTo(null) ; // CENTRA EL SEGUNDO FRAME EN LA PANTA
        ventana2_2.pack() ;
        ventana2_2.setResizable(true) ; // PERMITE REDIMENSIONAR
        ventana2_2.setVisible(true) ;
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Consultar_Soluciones(null, null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables

}
