/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Eliminar.java
 *
 * Created on 28-01-2012, 07:21:39 PM
 */

package grafica;
import java.awt.*;
import javax.swing.*;

import java.io.*;

/**
 *
 * @author Marcial
 */
public class Eliminar extends javax.swing.JFrame {

    ArbolNombres arbol_nombres;
    ArbolSintomas arbol_sintomas;

    /** Creates new form Eliminar */
    public Eliminar(ArbolNombres arbol_nombres, ArbolSintomas arbol_sintomas) {
        initComponents();
	this.arbol_nombres=arbol_nombres;
	this.arbol_sintomas=arbol_sintomas;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        toxicoEliminado = new javax.swing.JTextField();
        Eliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Agente a eliminar.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setBounds(20, 30, 345, 40);
        jDesktopPane1.add(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        toxicoEliminado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toxicoEliminadoActionPerformed(evt);
            }
        });
        toxicoEliminado.setBounds(20, 80, 160, 20);
        jDesktopPane1.add(toxicoEliminado, javax.swing.JLayeredPane.DEFAULT_LAYER);

        Eliminar.setText("Eliminar");
        Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarActionPerformed(evt);
            }
        });
        Eliminar.setBounds(160, 120, 90, 23);
        jDesktopPane1.add(Eliminar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarActionPerformed
	//buscamos en el arbol el compuesto o medicamento a eliminar
	String compuesto=this.toxicoEliminado.getText();

	try{
		Nodo nodo=this.arbol_nombres.BuscarCompuesto(compuesto);
		this.arbol_nombres.Eliminar(nodo);
		Fichero f=new Fichero();
		f.Escribir(this.arbol_nombres);
		
		
		JOptionPane.showMessageDialog(null, "Eliminado");

	}catch(ArbolNombres_NoEncontrado e){
		JOptionPane.showMessageDialog(null, "No se encontro el compuesto o medicamento a eliminar");
	}catch(Exception e) {
		
		JOptionPane.showMessageDialog(null, "No se puede abrir 'database.txt'");
	}
    }//GEN-LAST:event_EliminarActionPerformed

    private void toxicoEliminadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toxicoEliminadoActionPerformed
	    

    }//GEN-LAST:event_toxicoEliminadoActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Eliminar(null, null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Eliminar;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField toxicoEliminado;
    // End of variables declaration//GEN-END:variables

}
