/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Ingresar_Nuevo_Toxico.java
 *
 * Created on 28-01-2012, 06:45:08 PM
 */

package grafica;

/**
 *
 * @author Marcial
 */
public class Ingresar_Nuevo_Toxico extends javax.swing.JFrame {

    /** Creates new form Ingresar_Nuevo_Toxico */
    public Ingresar_Nuevo_Toxico() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        toxicoIngresado = new javax.swing.JTextField();
        sintomaIngresado = new javax.swing.JTextField();
        medicamentoIngresado = new javax.swing.JTextField();
        Guardar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ingresar agente toxico2.jpg"))); // NOI18N
        jLabel1.setBounds(40, 30, 178, 40);
        jDesktopPane1.add(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Ingrese sintomas que genera.jpg"))); // NOI18N
        jLabel2.setBounds(40, 130, 254, 40);
        jDesktopPane1.add(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ingresar agente medicamento.jpg"))); // NOI18N
        jLabel3.setBounds(40, 230, 180, 40);
        jDesktopPane1.add(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        toxicoIngresado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toxicoIngresadoActionPerformed(evt);
            }
        });
        toxicoIngresado.setBounds(40, 90, 180, 20);
        jDesktopPane1.add(toxicoIngresado, javax.swing.JLayeredPane.DEFAULT_LAYER);

        sintomaIngresado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sintomaIngresadoActionPerformed(evt);
            }
        });
        sintomaIngresado.setBounds(40, 190, 180, 20);
        jDesktopPane1.add(sintomaIngresado, javax.swing.JLayeredPane.DEFAULT_LAYER);

        medicamentoIngresado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medicamentoIngresadoActionPerformed(evt);
            }
        });
        medicamentoIngresado.setBounds(40, 290, 180, 20);
        jDesktopPane1.add(medicamentoIngresado, javax.swing.JLayeredPane.DEFAULT_LAYER);

        Guardar.setText("Guardar");
        Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarActionPerformed(evt);
            }
        });
        Guardar.setBounds(290, 310, 80, 23);
        jDesktopPane1.add(Guardar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 344, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void toxicoIngresadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toxicoIngresadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_toxicoIngresadoActionPerformed

    private void sintomaIngresadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sintomaIngresadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sintomaIngresadoActionPerformed

    private void medicamentoIngresadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medicamentoIngresadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_medicamentoIngresadoActionPerformed

    private void GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarActionPerformed
//Aqui debe ir
//Variable toxico=toxicoIngresado.getText();
//Variable sintoma=sintomaIngresado.getText();
//Variable medicamento=meicamentoIngresado.getText();

        // TODO add your handling code here:
    }//GEN-LAST:event_GuardarActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ingresar_Nuevo_Toxico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Guardar;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField medicamentoIngresado;
    private javax.swing.JTextField sintomaIngresado;
    private javax.swing.JTextField toxicoIngresado;
    // End of variables declaration//GEN-END:variables

}
