/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Modificar_Datos.java
 *
 * Created on 28-01-2012, 05:29:23 PM
 */

package grafica;

import java.awt.Dimension;

/**
 *
 * @author Marcial
 */
public class Modificar_Datos extends javax.swing.JFrame {

    /** Creates new form Modificar_Datos */
    public Modificar_Datos() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Ingresar.jpg"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.setBounds(50, 0, 70, 70);
        jDesktopPane1.add(jButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/editar.jpg"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jButton2.setBounds(50, 70, 70, 70);
        jDesktopPane1.add(jButton2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Busqueda.jpg"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jButton3.setBounds(50, 140, 70, 80);
        jDesktopPane1.add(jButton3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Eliminacion de agentes toxicos.jpg"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jButton4.setBounds(50, 220, 70, 80);
        jDesktopPane1.add(jButton4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ingresar agente toxico.jpg"))); // NOI18N
        jLabel1.setBounds(150, 20, 205, 40);
        jDesktopPane1.add(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/editar2.jpg"))); // NOI18N
        jLabel2.setBounds(150, 90, 60, 36);
        jDesktopPane1.add(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Buscar agente toxico.jpg"))); // NOI18N
        jLabel3.setBounds(150, 170, 152, 40);
        jDesktopPane1.add(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/eliminar.jpg"))); // NOI18N
        jLabel4.setBounds(150, 240, 73, 36);
        jDesktopPane1.add(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Editar ventana1_2 = new Editar();
        Dimension dlgSize = ventana1_2.getPreferredSize();
        Dimension pantalla = getSize();
        Dimension ventana = ventana1_2.getSize() ;
        ventana1_2.setLocation((pantalla.width - Editar.WIDTH ) / 2 ,(pantalla.height - Editar.HEIGHT) / 2);
        ventana1_2.setLocationRelativeTo(null) ; // CENTRA EL SEGUNDO FRAME EN LA PANTA
        ventana1_2.pack() ;
        ventana1_2.setResizable(true) ; // PERMITE REDIMENSIONAR
        ventana1_2.setVisible(true) ;
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Ingresar_Nuevo_Toxico ventana1_1 = new Ingresar_Nuevo_Toxico();
        Dimension dlgSize = ventana1_1.getPreferredSize();
        Dimension pantalla = getSize();
        Dimension ventana = ventana1_1.getSize() ;
        ventana1_1.setLocation((pantalla.width - Ingresar_Nuevo_Toxico.WIDTH ) / 2 ,(pantalla.height - Ingresar_Nuevo_Toxico.HEIGHT) / 2);
        ventana1_1.setLocationRelativeTo(null) ; // CENTRA EL SEGUNDO FRAME EN LA PANTA
        ventana1_1.pack() ;
        ventana1_1.setResizable(true) ; // PERMITE REDIMENSIONAR
        ventana1_1.setVisible(true) ;
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Buscar_Agente_Toxico ventana1_3 = new Buscar_Agente_Toxico();
        Dimension dlgSize = ventana1_3.getPreferredSize();
        Dimension pantalla = getSize();
        Dimension ventana = ventana1_3.getSize() ;
        ventana1_3.setLocation((pantalla.width - Buscar_Agente_Toxico.WIDTH ) / 2 ,(pantalla.height - Buscar_Agente_Toxico.HEIGHT) / 2);
        ventana1_3.setLocationRelativeTo(null) ; // CENTRA EL SEGUNDO FRAME EN LA PANTA
        ventana1_3.pack() ;
        ventana1_3.setResizable(true) ; // PERMITE REDIMENSIONAR
        ventana1_3.setVisible(true) ;
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        Eliminar ventana1_4 = new Eliminar();
        Dimension dlgSize = ventana1_4.getPreferredSize();
        Dimension pantalla = getSize();
        Dimension ventana = ventana1_4.getSize() ;
        ventana1_4.setLocation((pantalla.width - Eliminar.WIDTH ) / 2 ,(pantalla.height - Eliminar.HEIGHT) / 2);
        ventana1_4.setLocationRelativeTo(null) ; // CENTRA EL SEGUNDO FRAME EN LA PANTA
        ventana1_4.pack() ;
        ventana1_4.setResizable(true) ; // PERMITE REDIMENSIONAR
        ventana1_4.setVisible(true) ;
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Modificar_Datos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables

}
