/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Modificar_Datos.java
 *
 * Created on 28-01-2012, 05:29:23 PM
 */

package grafica;

import java.awt.Dimension;

/**
 *
 * @author Marcial
 */
public class Modificar_Datos extends javax.swing.JFrame {

    ArbolNombres arbol_nombres;
    ArbolSintomas arbol_sintomas;

    /** Creates new form Modificar_Datos */
    public Modificar_Datos(ArbolNombres arbol_nombres, ArbolSintomas arbol_sintomas) {
        initComponents();
	this.arbol_nombres=arbol_nombres;
	this.arbol_sintomas=arbol_sintomas;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Ingresar.jpg"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.setBounds(160, 60, 70, 70);
        jDesktopPane1.add(jButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ingresar agente toxico.jpg"))); // NOI18N
        jLabel1.setBounds(100, 170, 205, 40);
        jDesktopPane1.add(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Ingresar_Nuevo_Toxico ventana1_1 = new Ingresar_Nuevo_Toxico(this.arbol_nombres, this.arbol_sintomas);
        Dimension dlgSize = ventana1_1.getPreferredSize();
        Dimension pantalla = getSize();
        Dimension ventana = ventana1_1.getSize() ;
        ventana1_1.setLocation((pantalla.width - Ingresar_Nuevo_Toxico.WIDTH ) / 2 ,(pantalla.height - Ingresar_Nuevo_Toxico.HEIGHT) / 2);
        ventana1_1.setLocationRelativeTo(null) ; // CENTRA EL SEGUNDO FRAME EN LA PANTA
        ventana1_1.pack() ;
        ventana1_1.setResizable(true) ; // PERMITE REDIMENSIONAR
        ventana1_1.setVisible(true) ;
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Modificar_Datos(null, null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

}
