/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * respuesta_busca_tox.java
 *
 * Created on 04-02-2012, 08:26:24 PM
 */

package grafica;

import java.awt.Dimension;
import java.awt.*;
import javax.swing.*;

/**
 *
 * @author Marcial
 */
public class respuesta_busca_tox extends javax.swing.JFrame {

    Nodo nodo;
    ArbolNombres arbol_nombres;
    ArbolSintomas arbol_sintomas;

    /** Creates new form respuesta_busca_tox */
    public respuesta_busca_tox(Nodo nodo, ArbolNombres arbol_nombres, ArbolSintomas arbol_sintomas) {
        initComponents();

	this.nodo=nodo;

	this.arbol_nombres=arbol_nombres;
	this.arbol_sintomas=arbol_sintomas;

	this.NombreComp.setText(nodo.getNombreCompuesto());
	this.Nombre_medic.setText(nodo.getNombreMedicamento());
	this.Tratamiento.setText(nodo.getSolucion());
	
	String sintomas="";
	for(int i=0;i<nodo.getSintomas().size();i++)
	{
		sintomas+=nodo.getSintomas().elementAt(i)+",";
	}

	this.sintomas.setText(sintomas);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        respuestatox = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        NombreComp = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        Nombre_medic = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        sintomas = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Tratamiento = new javax.swing.JTextArea();
        Modificar = new javax.swing.JButton();
        BotonEliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Nombre Compuesto:");
        jLabel1.setBounds(20, 20, 190, 14);
        respuestatox.add(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        NombreComp.setBounds(20, 50, 190, 20);
        respuestatox.add(NombreComp, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel2.setText("Nombre medicamento:");
        jLabel2.setBounds(20, 90, 190, 14);
        respuestatox.add(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        Nombre_medic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Nombre_medicActionPerformed(evt);
            }
        });
        Nombre_medic.setBounds(20, 120, 190, 20);
        respuestatox.add(Nombre_medic, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel3.setText("Sintomas:");
        jLabel3.setBounds(20, 160, 120, 14);
        respuestatox.add(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        sintomas.setColumns(20);
        sintomas.setRows(5);
        jScrollPane1.setViewportView(sintomas);

        jScrollPane1.setBounds(20, 190, 310, 40);
        respuestatox.add(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel4.setText("Tratamiento:");
        jLabel4.setBounds(20, 250, 120, 14);
        respuestatox.add(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        Tratamiento.setColumns(20);
        Tratamiento.setRows(5);
        jScrollPane2.setViewportView(Tratamiento);

        jScrollPane2.setBounds(20, 280, 310, 40);
        respuestatox.add(jScrollPane2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        Modificar.setText("Modificar");
        Modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarActionPerformed(evt);
            }
        });
        Modificar.setBounds(183, 350, 150, 23);
        respuestatox.add(Modificar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        BotonEliminar.setText("Eliminar");
        BotonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonEliminarActionPerformed(evt);
            }
        });
        BotonEliminar.setBounds(20, 350, 140, 23);
        respuestatox.add(BotonEliminar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(respuestatox, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(respuestatox, javax.swing.GroupLayout.DEFAULT_SIZE, 413, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Nombre_medicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Nombre_medicActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Nombre_medicActionPerformed

    private void BotonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonEliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonEliminarActionPerformed

    private void ModificarActionPerformed(java.awt.event.ActionEvent evt) {                                          

	Nodo nodo=new Nodo();
	nodo.setNombreMedicamento(this.Nombre_medic.getText());
	nodo.setNombreCompuesto(this.NombreComp.getText());
	nodo.setSolucion(this.Tratamiento.getText());

	String []sintomas=this.sintomas.getText().split(",");
	for(int i=0;i<sintomas.length;i++)
	{
		nodo.AgregarSintoma(sintomas[i]);
	}

	//Borramos el nodo de esta clase con el nodo de this
	
	this.arbol_nombres.Eliminar(this.nodo);
	this.arbol_nombres.Agregar(nodo);

	this.nodo=nodo;
	
	//guardamos los cambios en la base de datos
	
	try{
		Fichero f=new Fichero();
		f.Escribir(this.arbol_nombres);
	}catch(Exception e){

		JOptionPane.showMessageDialog(null, "No se puede escribir en 'database.txt'");
	}

    }

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new respuesta_busca_tox(null, null, null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonEliminar;
    private javax.swing.JButton Modificar;
    private javax.swing.JTextField NombreComp;
    private javax.swing.JTextField Nombre_medic;
    private javax.swing.JTextArea Tratamiento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JDesktopPane respuestatox;
    private javax.swing.JTextArea sintomas;
    // End of variables declaration//GEN-END:variables

}
