/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Sintomas.java
 *
 * Created on 28-01-2012, 06:13:47 PM
 */

package grafica;

import java.util.Vector;

/**
 *
 * @author Marcial
 */
public class Sintomas extends javax.swing.JFrame {

	ArbolNombres arbol_nombres;
	ArbolSintomas arbol_sintomas;

    /** Creates new form Sintomas */
    public Sintomas(ArbolNombres arbol_nombres, ArbolSintomas arbol_sintomas) {
        initComponents();
	this.arbol_nombres=arbol_nombres;
	this.arbol_sintomas=arbol_sintomas;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        sintomasIngresados = new javax.swing.JTextField();
        buscarSolucion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Ingrese2.jpg"))); // NOI18N
        jLabel1.setBounds(30, 20, 139, 40);
        jDesktopPane1.add(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        sintomasIngresados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sintomasIngresadosActionPerformed(evt);
            }
        });
        sintomasIngresados.setBounds(30, 80, 310, 20);
        jDesktopPane1.add(sintomasIngresados, javax.swing.JLayeredPane.DEFAULT_LAYER);

        buscarSolucion.setText("Buscar Solucion");
        buscarSolucion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarSolucionActionPerformed(evt);
            }
        });
        buscarSolucion.setBounds(120, 120, 130, 23);
        jDesktopPane1.add(buscarSolucion, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sintomasIngresadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sintomasIngresadosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sintomasIngresadosActionPerformed

    private void buscarSolucionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarSolucionActionPerformed

	//debemos ver si el usuario ha ingresado algo
	
	if(sintomasIngresados.getText()==null)
	{
		System.out.println("Debe ingresar los sintomas a buscar");
	}else{
		//buscamos los sintomas en el arbol
		try{
			String []sintomas=sintomasIngresados.getText().split(",");

			Vector<String> vector=new Vector();

			int i;
			for(i=0;i<sintomas.length;i++)
			{
				vector.add(sintomas[i]);
			}

			if(vector.size()>=1)
			{
				Vector <String> mejor=this.arbol_sintomas.mejorSolucion(this.arbol_sintomas.BuscarSintoma(vector));

				System.out.println(mejor.elementAt(0));

				Nodo nodo=this.arbol_nombres.BuscarMedicamento(mejor.elementAt(0));
				System.out.println(nodo.getNombreCompuesto());
			}


		}catch(ArbolSintomasNoEncontrado e){
			System.out.println("Sintoma no encontrado");
		}catch(ArbolNombres_NoEncontrado e){
			System.out.println("Compuesto o medicamento no encontrado");
		}
	}

    }//GEN-LAST:event_buscarSolucionActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sintomas(null, null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buscarSolucion;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField sintomasIngresados;
    // End of variables declaration//GEN-END:variables

}
