/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Sustancia.java
 *
 * Created on 28-01-2012, 06:05:23 PM
 */

package grafica;
import java.awt.*;
import javax.swing.*;

import java.io.*;

/**
 *
 * @author Marcial
 */
public class Sustancia extends javax.swing.JFrame {

	ArbolNombres arbol_nombres;
	ArbolSintomas arbol_sintomas;

    /** Creates new form Sustancia */
    public Sustancia(ArbolNombres arbol_nombres, ArbolSintomas arbol_sintomas) {
        initComponents();
	this.arbol_sintomas=arbol_sintomas;
	this.arbol_nombres=arbol_nombres;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        sustanciaIngresada = new javax.swing.JTextField();
        buscarSolucion = new javax.swing.JButton();
        medicamentoSustancia = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        label1 = new java.awt.Label();
        label2 = new java.awt.Label();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        sustanciaIngresada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sustanciaIngresadaActionPerformed(evt);
            }
        });
        sustanciaIngresada.setBounds(40, 90, 210, 20);
        jDesktopPane1.add(sustanciaIngresada, javax.swing.JLayeredPane.DEFAULT_LAYER);

        buscarSolucion.setText("Buscar Solucion");
        buscarSolucion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarSolucionActionPerformed(evt);
            }
        });
        buscarSolucion.setBounds(210, 190, 170, 23);
        jDesktopPane1.add(buscarSolucion, javax.swing.JLayeredPane.DEFAULT_LAYER);

        medicamentoSustancia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medicamentoSustanciaActionPerformed(evt);
            }
        });
        medicamentoSustancia.setBounds(40, 150, 210, 20);
        jDesktopPane1.add(medicamentoSustancia, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Ingrese.jpg"))); // NOI18N
        jLabel2.setBounds(40, 20, 150, 40);
        jDesktopPane1.add(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        label1.setText("Medicamento:");
        label1.setBounds(40, 70, 90, 20);
        jDesktopPane1.add(label1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        label2.setText("Compuesto: ");
        label2.setBounds(40, 130, 120, 20);
        jDesktopPane1.add(label2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buscarSolucionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarSolucionActionPerformed

	Nodo nodo=null;
	if(this.medicamentoSustancia.getText().length()!=0 && this.sustanciaIngresada.getText().length()==0)
	{
		try{
			nodo=this.arbol_nombres.BuscarCompuesto(this.medicamentoSustancia.getText());
		}catch(ArbolNombres_NoEncontrado e){
			
			JOptionPane.showMessageDialog(null, "No se encontro el medicamento buscardo");
		}
	}else if(this.sustanciaIngresada.getText().length()!=0 && this.medicamentoSustancia.getText().length()==0){
		try{
			nodo=this.arbol_nombres.BuscarMedicamento(this.sustanciaIngresada.getText());
		}catch(ArbolNombres_NoEncontrado e){
			
			JOptionPane.showMessageDialog(null, "No se encontro el compuesto buscado");
		}
	}else if(this.sustanciaIngresada.getText().length()!=0 && this.medicamentoSustancia.getText().length()!=0){
		try{
			nodo=this.arbol_nombres.BuscarCompuesto(this.sustanciaIngresada.getText());
		}catch(ArbolNombres_NoEncontrado e){
			
			JOptionPane.showMessageDialog(null, "No se encontro el compuesto buscardo");
		}

		JOptionPane.showMessageDialog(null, "Ha buscado un compuesto y un medicamento al mismo tiempo, se ha buscado por el nombre del compuesto solamente para evitar conflictos");
	}else{
		
		JOptionPane.showMessageDialog(null, "Debe ingresar un compuesto o medicamento a buscar");
	}

	if(nodo!=null)
	{
		new respuesta_busca_tox(nodo, this.arbol_nombres, this.arbol_sintomas).setVisible(true);
	}

    }//GEN-LAST:event_buscarSolucionActionPerformed

    private void sustanciaIngresadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sustanciaIngresadaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sustanciaIngresadaActionPerformed

    private void medicamentoSustanciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medicamentoSustanciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_medicamentoSustanciaActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sustancia(null, null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buscarSolucion;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel2;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private javax.swing.JTextField medicamentoSustancia;
    private javax.swing.JTextField sustanciaIngresada;
    // End of variables declaration//GEN-END:variables

}
