/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Sustancia.java
 *
 * Created on 28-01-2012, 06:05:23 PM
 */

package grafica;

/**
 *
 * @author Marcial
 */
public class Sustancia extends javax.swing.JFrame {

    /** Creates new form Sustancia */
    public Sustancia() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        sustanciaIngresada = new javax.swing.JTextField();
        buscarSolucion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Ingrese.jpg"))); // NOI18N
        jLabel1.setBounds(40, 20, 150, 40);
        jDesktopPane1.add(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        sustanciaIngresada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sustanciaIngresadaActionPerformed(evt);
            }
        });
        sustanciaIngresada.setBounds(40, 80, 210, 20);
        jDesktopPane1.add(sustanciaIngresada, javax.swing.JLayeredPane.DEFAULT_LAYER);

        buscarSolucion.setText("Buscar Solucion");
        buscarSolucion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarSolucionActionPerformed(evt);
            }
        });
        buscarSolucion.setBounds(120, 130, 170, 23);
        jDesktopPane1.add(buscarSolucion, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buscarSolucionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarSolucionActionPerformed
        //Variable Sustancia Ingresada=sustanciaIngresada.getText();
    }//GEN-LAST:event_buscarSolucionActionPerformed

    private void sustanciaIngresadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sustanciaIngresadaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sustanciaIngresadaActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sustancia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buscarSolucion;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField sustanciaIngresada;
    // End of variables declaration//GEN-END:variables

}
